version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 20
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 20
