#!/bin/sh
go get -v github.com/aws/aws-sdk-go/aws/...
go get -v github.com/aws/aws-sdk-go/service/ec2/...
go get -v github.com/aws/aws-sdk-go/service/s3/...
go get -v github.com/satori/go.uuid
go get -v github.com/Sirupsen/logrus
go get -v github.com/sebest/logrusly
